/**
 * Custom hook for managing requirement selection (bulk actions)
 * 
 * @module hooks/useRequirementSelection
 */

import { useState, useEffect, useCallback, useMemo } from 'react'
import { SubmissionRequirement } from '../lib/submissionRequirements'

export interface UseRequirementSelectionOptions {
  requirements: SubmissionRequirement[]
}

/**
 * Hook for managing selection state and bulk actions
 */
export function useRequirementSelection(options: UseRequirementSelectionOptions) {
  const { requirements } = options
  const [selectedRequirements, setSelectedRequirements] = useState<Set<string>>(new Set())
  const [selectAll, setSelectAll] = useState<boolean>(false)

  // Update select all state when requirements or selection changes
  useEffect(() => {
    if (requirements.length > 0) {
      const allSelected = requirements.every(req => selectedRequirements.has(req.id))
      setSelectAll(allSelected)
    } else {
      setSelectAll(false)
    }
  }, [requirements, selectedRequirements])

  // Clear selection when requirements change significantly
  useEffect(() => {
    if (selectedRequirements.size > 0 && requirements.length > 0) {
      const hasSelectedInList = Array.from(selectedRequirements).some(id =>
        requirements.some(req => req.id === id)
      )
      if (!hasSelectedInList) {
        // Selection is completely outside current list, clear it
        setSelectedRequirements(new Set())
        setSelectAll(false)
      }
    }
  }, [requirements, selectedRequirements])

  const handleSelectAll = useCallback((checked: boolean) => {
    if (checked) {
      const allIds = new Set(requirements.map(req => req.id))
      setSelectedRequirements(allIds)
      setSelectAll(true)
    } else {
      setSelectedRequirements(new Set())
      setSelectAll(false)
    }
  }, [requirements])

  const handleSelectRequirement = useCallback((id: string, checked: boolean) => {
    setSelectedRequirements(prev => {
      const newSelected = new Set(prev)
      if (checked) {
        newSelected.add(id)
      } else {
        newSelected.delete(id)
      }
      return newSelected
    })
  }, [])

  const clearSelection = useCallback(() => {
    setSelectedRequirements(new Set())
    setSelectAll(false)
  }, [])

  // Get deletable requirements (exclude auto-generated)
  const deletableRequirements = useMemo(() => {
    return requirements.filter(
      req => selectedRequirements.has(req.id) && !req.is_auto_generated
    )
  }, [requirements, selectedRequirements])

  const autoGeneratedCount = useMemo(() => {
    return selectedRequirements.size - deletableRequirements.length
  }, [selectedRequirements.size, deletableRequirements.length])

  return {
    selectedRequirements,
    selectAll,
    handleSelectAll,
    handleSelectRequirement,
    clearSelection,
    deletableRequirements,
    autoGeneratedCount
  }
}
