"""add_website_to_tenants

Revision ID: c723883c0e24
Revises: 1766453013
Create Date: 2025-12-22 18:16:01.456845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c723883c0e24'
down_revision = '1766453013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'website')
    # ### end Alembic commands ###

